mail:       
      send_notification_mail: True
      mail_receipients: 
            - espen.korra@digdir.no

projects: 
      - product/autorisasjon
      - product/varsling
      - product/dialogporten.js

report_name: roadmap_report_test

latest_release_url: 'https://api.github.com/repos/ekorra/digdir-roadmap-util/releases/latest'

devlop_mode: True

