mail:       
      send_notification_mail: True
      mail_receipients: 
            - espen.korra@digdir.no

projects: 
      - product/autorisasjon
      - product/fdk
      - product/meldingstjenesten
      - product/dan
      - product/formidling
      - product/studio
      - product/dialogporten
      - product/arbeidsflaten
      - product/varsling
      - product/dialogporten.js

report_name: roadmap_report

latest_release_url: 'https://api.github.com/repos/ekorra/digdir-roadmap-util/releases/latest'

devlop_mode: False





